using static System.Convert;
using static SplashKitSDK.SplashKit;

//define variables.
String name, things;
String userInput;
double dollars, time;
double predollars, weeklymoney;
double weeklyneedsavemoney, cuweek;

// prompt the user to enter their name.
Write("What is you name?:");
name = ReadLine();
WriteLine();
WriteLine($"Hi {name}");
WriteLine();

// Ask about the purpose of saving money.
Write("What are you saving for?");
things = ReadLine();

// Ask how much more money is needed.
Write("How much do you need to save? ");
userInput = ReadLine();
dollars = ToDouble(userInput);

// Ask about the remaining time.
Write("How long before the purchase? ");
userInput = ReadLine();
time = ToDouble(userInput);

// Ask about the money that is already availiable.
Write("How much do you have already? ");
userInput = ReadLine();
predollars = ToDouble(userInput);

// Ask about the ability to save money to prepare for the estimated time.
Write("How much can you save each week?");
userInput = ReadLine();
weeklymoney = ToDouble(userInput);

// Data generated by calculation
weeklyneedsavemoney = (dollars - predollars) / time;
cuweek = (dollars - predollars) / weeklymoney;

// Output result
WriteLine($"For the Holiday, you need to save {weeklyneedsavemoney} dollars a week");
WriteLine($"Based on current savings you will need {cuweek} weeks to save {dollars}");
